-- CreateTable
CREATE TABLE "DocumentStructureSection" (
    "id" SERIAL NOT NULL,
    "tipoSigla" TEXT NOT NULL,
    "titulo" TEXT NOT NULL,
    "activa" BOOLEAN NOT NULL DEFAULT true,
    "orden" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DocumentStructureSection_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "DocumentStructureSection_tipoSigla_orden_idx" ON "DocumentStructureSection"("tipoSigla", "orden");

-- Seed the per-type recommended outlines Control Documental's "Estructuras
-- documentales" tab has always shown (ESTRUCTURAS_INI in
-- frontend/src/routes/ControlDocumental.jsx). Until now this lived only in the
-- component's React state and was lost on reload; persisting it here makes an
-- admin's edits (add / rename / reorder / uncheck a section) survive leaving
-- the page. Only runs when the table is empty, so it is safe against a
-- database an admin has already customized.
INSERT INTO "DocumentStructureSection" ("tipoSigla", "titulo", "activa", "orden", "updatedAt")
SELECT * FROM (VALUES
    ('POL', 'Título', true, 0, CURRENT_TIMESTAMP),
    ('POL', 'Propósito', true, 1, CURRENT_TIMESTAMP),
    ('POL', 'Alcance', true, 2, CURRENT_TIMESTAMP),
    ('POL', 'Principios y compromisos', true, 3, CURRENT_TIMESTAMP),
    ('POL', 'Lineamientos', true, 4, CURRENT_TIMESTAMP),
    ('POL', 'Responsabilidades', true, 5, CURRENT_TIMESTAMP),
    ('POL', 'Comunicación', true, 6, CURRENT_TIMESTAMP),
    ('POL', 'Revisión', true, 7, CURRENT_TIMESTAMP),
    ('POL', 'Aprobación', true, 8, CURRENT_TIMESTAMP),
    ('MAN', 'Objetivo', true, 0, CURRENT_TIMESTAMP),
    ('MAN', 'Alcance', true, 1, CURRENT_TIMESTAMP),
    ('MAN', 'Referencias', true, 2, CURRENT_TIMESTAMP),
    ('MAN', 'Definiciones', true, 3, CURRENT_TIMESTAMP),
    ('MAN', 'Contexto de la organización', true, 4, CURRENT_TIMESTAMP),
    ('MAN', 'Estructura organizacional', true, 5, CURRENT_TIMESTAMP),
    ('MAN', 'Descripción del sistema', true, 6, CURRENT_TIMESTAMP),
    ('MAN', 'Procesos', true, 7, CURRENT_TIMESTAMP),
    ('MAN', 'Interacción de procesos', true, 8, CURRENT_TIMESTAMP),
    ('MAN', 'Responsabilidades', true, 9, CURRENT_TIMESTAMP),
    ('MAN', 'Información documentada relacionada', true, 10, CURRENT_TIMESTAMP),
    ('MAN', 'Anexos', true, 11, CURRENT_TIMESTAMP),
    ('PRO', 'Objetivo', true, 0, CURRENT_TIMESTAMP),
    ('PRO', 'Alcance', true, 1, CURRENT_TIMESTAMP),
    ('PRO', 'Referencias', true, 2, CURRENT_TIMESTAMP),
    ('PRO', 'Definiciones', true, 3, CURRENT_TIMESTAMP),
    ('PRO', 'Responsabilidades', true, 4, CURRENT_TIMESTAMP),
    ('PRO', 'Desarrollo del procedimiento', true, 5, CURRENT_TIMESTAMP),
    ('PRO', 'Diagrama de flujo', true, 6, CURRENT_TIMESTAMP),
    ('PRO', 'Controles', true, 7, CURRENT_TIMESTAMP),
    ('PRO', 'Registros generados', true, 8, CURRENT_TIMESTAMP),
    ('PRO', 'Indicadores', true, 9, CURRENT_TIMESTAMP),
    ('PRO', 'Anexos', true, 10, CURRENT_TIMESTAMP),
    ('PRO', 'Historial de cambios', true, 11, CURRENT_TIMESTAMP),
    ('PRG', 'Objetivo', true, 0, CURRENT_TIMESTAMP),
    ('PRG', 'Alcance', true, 1, CURRENT_TIMESTAMP),
    ('PRG', 'Responsables', true, 2, CURRENT_TIMESTAMP),
    ('PRG', 'Actividades', true, 3, CURRENT_TIMESTAMP),
    ('PRG', 'Frecuencia', true, 4, CURRENT_TIMESTAMP),
    ('PRG', 'Recursos', true, 5, CURRENT_TIMESTAMP),
    ('PRG', 'Indicadores', true, 6, CURRENT_TIMESTAMP),
    ('PRG', 'Registros', true, 7, CURRENT_TIMESTAMP),
    ('PLA', 'Objetivo', true, 0, CURRENT_TIMESTAMP),
    ('PLA', 'Alcance', true, 1, CURRENT_TIMESTAMP),
    ('PLA', 'Actividades', true, 2, CURRENT_TIMESTAMP),
    ('PLA', 'Responsables', true, 3, CURRENT_TIMESTAMP),
    ('PLA', 'Recursos', true, 4, CURRENT_TIMESTAMP),
    ('PLA', 'Cronograma', true, 5, CURRENT_TIMESTAMP),
    ('PLA', 'Criterios de control', true, 6, CURRENT_TIMESTAMP),
    ('PLA', 'Registros', true, 7, CURRENT_TIMESTAMP),
    ('INS', 'Objetivo', true, 0, CURRENT_TIMESTAMP),
    ('INS', 'Alcance', true, 1, CURRENT_TIMESTAMP),
    ('INS', 'Responsable', true, 2, CURRENT_TIMESTAMP),
    ('INS', 'Recursos y materiales', true, 3, CURRENT_TIMESTAMP),
    ('INS', 'Precauciones', true, 4, CURRENT_TIMESTAMP),
    ('INS', 'Instrucciones paso a paso', true, 5, CURRENT_TIMESTAMP),
    ('INS', 'Criterios de aceptación', true, 6, CURRENT_TIMESTAMP),
    ('INS', 'Registros', true, 7, CURRENT_TIMESTAMP),
    ('INS', 'Anexos', true, 8, CURRENT_TIMESTAMP),
    ('ESP', 'Identificación', true, 0, CURRENT_TIMESTAMP),
    ('ESP', 'Características y requisitos', true, 1, CURRENT_TIMESTAMP),
    ('ESP', 'Límites y criterios de aceptación', true, 2, CURRENT_TIMESTAMP),
    ('ESP', 'Método de evaluación', true, 3, CURRENT_TIMESTAMP),
    ('ESP', 'Referencias', true, 4, CURRENT_TIMESTAMP),
    ('ESP', 'Aprobación', true, 5, CURRENT_TIMESTAMP),
    ('FT', 'Identificación', true, 0, CURRENT_TIMESTAMP),
    ('FT', 'Descripción', true, 1, CURRENT_TIMESTAMP),
    ('FT', 'Características', true, 2, CURRENT_TIMESTAMP),
    ('FT', 'Especificaciones', true, 3, CURRENT_TIMESTAMP),
    ('FT', 'Métodos de análisis', true, 4, CURRENT_TIMESTAMP),
    ('FT', 'Condiciones de almacenamiento', true, 5, CURRENT_TIMESTAMP),
    ('FT', 'Vida útil', true, 6, CURRENT_TIMESTAMP),
    ('FT', 'Referencias', true, 7, CURRENT_TIMESTAMP),
    ('PTC', 'Objetivo', true, 0, CURRENT_TIMESTAMP),
    ('PTC', 'Alcance', true, 1, CURRENT_TIMESTAMP),
    ('PTC', 'Responsables', true, 2, CURRENT_TIMESTAMP),
    ('PTC', 'Metodología', true, 3, CURRENT_TIMESTAMP),
    ('PTC', 'Equipos y materiales', true, 4, CURRENT_TIMESTAMP),
    ('PTC', 'Criterios de aceptación', true, 5, CURRENT_TIMESTAMP),
    ('PTC', 'Resultados', true, 6, CURRENT_TIMESTAMP),
    ('PTC', 'Conclusiones', true, 7, CURRENT_TIMESTAMP),
    ('MAT', 'Objetivo o identificación', true, 0, CURRENT_TIMESTAMP),
    ('MAT', 'Variables', true, 1, CURRENT_TIMESTAMP),
    ('MAT', 'Responsables', true, 2, CURRENT_TIMESTAMP),
    ('MAT', 'Criterios', true, 3, CURRENT_TIMESTAMP),
    ('MAT', 'Estado', true, 4, CURRENT_TIMESTAMP),
    ('MAT', 'Evidencia', true, 5, CURRENT_TIMESTAMP),
    ('FOR', 'Identificación', true, 0, CURRENT_TIMESTAMP),
    ('FOR', 'Código', true, 1, CURRENT_TIMESTAMP),
    ('FOR', 'Versión', true, 2, CURRENT_TIMESTAMP),
    ('FOR', 'Campos requeridos', true, 3, CURRENT_TIMESTAMP),
    ('FOR', 'Responsable del registro', true, 4, CURRENT_TIMESTAMP),
    ('REG', 'Identificación', true, 0, CURRENT_TIMESTAMP),
    ('REG', 'Fecha', true, 1, CURRENT_TIMESTAMP),
    ('REG', 'Responsable', true, 2, CURRENT_TIMESTAMP),
    ('REG', 'Datos y evidencia', true, 3, CURRENT_TIMESTAMP),
    ('REG', 'Resultado', true, 4, CURRENT_TIMESTAMP),
    ('REG', 'Aprobación cuando aplique', true, 5, CURRENT_TIMESTAMP),
    ('LST', 'Código', true, 0, CURRENT_TIMESTAMP),
    ('LST', 'Documento', true, 1, CURRENT_TIMESTAMP),
    ('LST', 'Proceso', true, 2, CURRENT_TIMESTAMP),
    ('LST', 'Versión', true, 3, CURRENT_TIMESTAMP),
    ('LST', 'Fecha de aprobación', true, 4, CURRENT_TIMESTAMP),
    ('LST', 'Vigencia', true, 5, CURRENT_TIMESTAMP),
    ('LST', 'Responsable', true, 6, CURRENT_TIMESTAMP),
    ('LST', 'Estado', true, 7, CURRENT_TIMESTAMP),
    ('LST', 'Ubicación', true, 8, CURRENT_TIMESTAMP),
    ('DOC-EXT', 'Identificación', true, 0, CURRENT_TIMESTAMP),
    ('DOC-EXT', 'Fuente o emisor', true, 1, CURRENT_TIMESTAMP),
    ('DOC-EXT', 'Versión o edición', true, 2, CURRENT_TIMESTAMP),
    ('DOC-EXT', 'Fecha de verificación de vigencia', true, 3, CURRENT_TIMESTAMP),
    ('DOC-EXT', 'Requisitos aplicables', true, 4, CURRENT_TIMESTAMP),
    ('DOC-EXT', 'Responsable', true, 5, CURRENT_TIMESTAMP),
    ('DOC-EXT', 'Ubicación', true, 6, CURRENT_TIMESTAMP)
) AS seed("tipoSigla", "titulo", "activa", "orden", "updatedAt")
WHERE NOT EXISTS (SELECT 1 FROM "DocumentStructureSection");
