-- `Document.type` goes from the `DocumentType` enum to free text, so a
-- document created from Control Documental can be any row of the
-- `DocumentTypeCatalog` table (Programa, Instructivo, Ficha técnica, …),
-- not just the 5 enum values. `DocumentTemplate.type` keeps the enum.
--
-- In-place cast (Prisma's autogenerated version drops + recreates the
-- column, which would lose data). Postgres rebuilds `Document_type_idx`
-- automatically as part of the type change.
ALTER TABLE "Document" ALTER COLUMN "type" TYPE TEXT USING "type"::text;

-- The `DocumentType` enum type stays in the database — `DocumentTemplate.type`
-- still uses it.
